/**
 * Stable, machine-readable error codes owned by this service.
 * Kept intentionally generic for authentication failures to avoid
 * account enumeration (see AppError usages in routes/v1/auth).
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',

  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  PHONE_ALREADY_VERIFIED: 'PHONE_ALREADY_VERIFIED',

  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',

  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_NOT_REQUESTED: 'OTP_NOT_REQUESTED',

  GOOGLE_OAUTH_NOT_CONFIGURED: 'GOOGLE_OAUTH_NOT_CONFIGURED',
  GOOGLE_OAUTH_FAILED: 'GOOGLE_OAUTH_FAILED',
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',

  INTERNAL_AUTH_FAILED: 'INTERNAL_AUTH_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
